# Use root/example as user/password credentials
version: '3.1'

services:

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: r1
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
        -   3306:3306
        volumes:
        -   mariadb-data:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080
    redis:
        image: redis
        ports:
        -   6379:6379
volumes:
    mariadb-data:
